- name: Appliquer le nouveau mot de passe sur les machines Windows
  hosts: windows
  become: false
  vars_files:
    - ../conf/secrets.yml
  tasks:
    - name: Générer un nouveau mot de passe pour Windows
      win_shell: |
        $pass = -join ((65..90) + (97..122) | Get-Random -Count 12 | % {[char]$_}) + "!"
        $pass | Out-String | ForEach-Object { $_.Trim() }
      register: windows_password
      

    - name: Changer le mot de passe de l'utilisateur Active Directory
      microsoft.ad.user:
        name: "{{ ansible_user_windows }}"
        password: "{{ windows_password.stdout }}"
        update_password: always
      delegate_to: windows # Exécutez cette tâche sur le contrôleur de domaine ou assurez-vous que la machine cible peut effectuer des modifications AD.

    - name: Mettre à jour le mot de passe Windows dans le Vault
      lineinfile:
        path: ../conf/secrets.yml
        regexp: '^windows_ansible_password:.*$'
        line: "windows_ansible_password: '{{ windows_password.stdout | trim }}'"
      delegate_to: localhost
      when: windows_password is defined


- name: Appliquer le nouveau mot de passe sur les machines Linux
  hosts: linux
  vars_files:
    - ../conf/secrets.yml
  become: true
  tasks:
    - name: Générer un nouveau mot de passe pour Linux
      shell: openssl rand -base64 12 | tr -d '\n'
      register: linux_password

    - name: Changer le mot de passe de l'utilisateur Linux
      user:
        name: "{{ ansible_user_linux }}"
        password: "{{ linux_password.stdout | password_hash('sha512') }}"

    - name: Mettre à jour le mot de passe Linux dans le Vault
      lineinfile:
        path: ../conf/secrets.yml
        regexp: '^linux_ansible_password:.*$'
        line: "linux_ansible_password: {{ linux_password.stdout }}"
      delegate_to: localhost
      when: linux_password is defined
