- name: Retirer la supervision Centreon pour les hôtes Windows et Linux
  hosts: Centreon
  gather_facts: no
  vars_files:
    - ../conf/secrets.yml
  tasks:
    - name: Obtenir le token d'authentification de l'API Centreon
      uri:
        url: "http://192.168.0.3/centreon/api/index.php?action=authenticate"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ centreon_admin_user }}"
          password: "{{ centreon_admin_password }}"
        return_content: yes
      register: login_response

    - name: Vérifier si l'hôte Windows existe dans Centreon
      uri:
        url: "http://192.168.0.3/centreon/api/index.php?action=action&object=centreon_clapi"
        method: POST
        body_format: json
        headers:
          centreon-auth-token: "{{ login_response.json.authToken }}"
        body:
          action: "show"
          object: "host"
          values: "WindowsHost"
        return_content: yes
      register: host_win_check
      delegate_to: localhost

    - name: Supprimer l'hôte Windows de Centreon si existant
      uri:
        url: "http://192.168.0.3/centreon/api/index.php?action=action&object=centreon_clapi"
        method: POST
        body_format: json
        headers:
          centreon-auth-token: "{{ login_response.json.authToken }}"
        body:
          action: "del"
          object: "host"
          values: "WindowsHost"
      when: "'WindowsHost' in host_win_check.content"
      delegate_to: localhost

- name: Désinstaller SNMP des hôtes Windows
  hosts: windows
  become: false
  vars_files:
    - secrets.yml
  tasks:
    - name: Désinstaller la fonctionnalité SNMP
      ansible.windows.win_feature:
        name: SNMP-Service
        state: absent
