- name: Retirer la supervision Centreon pour les hôtes Linux
  hosts: Centreon
  gather_facts: no
  vars_files:
    - ../conf/secrets.yml
  tasks:
    - name: Obtenir le token d'authentification de l'API Centreon
      uri:
        url: "http://192.168.0.3/centreon/api/index.php?action=authenticate"
        method: POST
        body_format: form-urlencoded
        body:
          username: "{{ centreon_admin_user }}"
          password: "{{ centreon_admin_password }}"
        return_content: yes
      register: login_response

    - name: Vérifier si l'hôte Linux existe dans Centreon
      uri:
        url: "http://192.168.0.3/centreon/api/index.php?action=action&object=centreon_clapi"
        method: POST
        body_format: json
        headers:
          centreon-auth-token: "{{ login_response.json.authToken }}"
        body:
          action: "show"
          object: "host"
          values: "LinuxHost"
        return_content: yes
      register: host_check
      delegate_to: localhost

    - name: Supprimer l'hôte Linux de Centreon si existant
      uri:
        url: "http://192.168.0.3/centreon/api/index.php?action=action&object=centreon_clapi"
        method: POST
        body_format: json
        headers:
          centreon-auth-token: "{{ login_response.json.authToken }}"
        body:
          action: "del"
          object: "host"
          values: "LinuxHost"
      when: "'LinuxHost' in host_check.content"
      delegate_to: localhost

- name: Désinstaller SNMP des hôtes Linux
  hosts: linux
  become: true
  tasks:
    - name: Désactiver et arrêter le service SNMP
      ansible.builtin.service:
        name: snmpd
        enabled: false
        state: stopped

    - name: Désinstaller SNMP
      ansible.builtin.package:
        name: snmpd
        state: absent
